### ISSUE TITLE
As of 0.1.19 throws Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by rsercano** [DispatchMe/meteor-mocha-phantomjs#35] opened 2016-12-05 17:07 UTC
Hello,

first of all, thanks for great work. But as you've published 0.1.19 now it stopped working. Check these build logs: 
[Success](https://travis-ci.org/rsercano/mongoclient/builds/181108298)
[Fail](https://travis-ci.org/rsercano/mongoclient/builds/181403059)

There's no difference in .yml file except dispatch mocha's version.

Could you please check ?
Cheers,
Sercan

**Comment by aldeed** [comment] 2016-12-06 20:49
@rsercano I believe this is because of the Meteor changes regarding binary packages. It is technically an issue with `dispatch:phantomjs-tests` package, which has a binary NPM dependency.

Essentially the change is that you are now responsible for rebuilding binary packages. So I think you can resolve this by running `meteor npm rebuild` command after `meteor add dispatch:mocha-phantomjs` in your travis script.

See:
- https://forums.meteor.com/t/whats-happening-to-meteor-publish-for-arch-in-meteor-1-4-1/28209
- https://guide.meteor.com/v1.4/1.4-migration.html#binary-packages-require-build-toolchain

If you are still having trouble, I suggest a github issue in the meteor repo. Let me know if the rebuild command resolves this for you. I can add that to the readme.

**Comment by rsercano** [comment] 2016-12-07 07:08
No sorry, [still same](https://travis-ci.org/rsercano/mongoclient/builds/181878635).  

But I couldn't get your point, did meteor change binary packages without publishing a release ? It's not been a while between my successful and fail builds, and I'm sure meteor version is still same.

**Comment by FinalDes** [comment] 2016-12-07 11:07
I get the same error after meteor npm rebuild

**Comment by HenrikSkriver** [comment] 2016-12-14 10:02
Hi @rsercano & @aldeed 

I believe I am experiencing the same issue and I would like to share the setup to verify.
Any input is very much appreciated.

Running this test command inside a Docker container based on debian:jessie with Meteor 1.4.2.3 installed:

`meteor test --once --driver-package dispatch:mocha-phantomjs`

results in the server tests being run but the client tests fail with this:

`
/root/.meteor/packages/dispatch_phantomjs-tests/.0.0.7.eppoq7++os+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: 1: /root/.meteor/packages/dispatch_phantomjs-tests/.0.0.7.eppoq7++os+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
`

The meteor app was copied into the image and meteor npm install was executed from within the container.

I am using these versions of the dispatch packages:

`dispatch:mocha-phantomjs@0.1.9
dispatch:phantomjs-tests@0.0.7`

As I understand from this thread, the problem seems to be that phantomjs-tests depends in [phantomjs-prebuilt](https://github.com/Medium/phantomjs#cross-platform-repositories) but the resolved version of this npm pacakage is not for this platform.

**Is that a correct understanding and if so are there any known workarounds?**

The tests are running fine on a Mac btw.

**Comment by jbbr** [comment] 2016-12-14 14:51
I can confirm this problem. It might be related to meteor/meteor#8014

This should normally be fixed by running `meteor npm rebuild` but this doesn't seems to be the case.
Maybe it's because the problematic phantomjs-prebuild package is installed globally in `~/.meteor/packages/..../node_modules/...` and not locally in the projects node_modules folder

I found two different workaround:

- Add this to your `.meteor/packages`: `dispatch:phantomjs-tests@=0.0.5`
This might require a `meteor update --allow-incompatible-update` as `dispatch:mocha-phantomjs` needs a downgrade too.
This pins `dispatch:phantomjs-tests` to the last working version. The difference according to `meteor show --ejson` is that since 0.0.6 the package is arch-independant.

```
// < 0.0.5
"architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os.windows.x86_32"
      ]
// >= 0.0.6
"architecturesOS": [
        "os"
      ]
```

- clone the git repo of the `dispatch:phantomjs-tests` into your `packages` folder. This way meteor will really rebuild the package includings its npm dependencies and you can use it without downgrading anything.

```
cd packages
git clone https://github.com/DispatchMe/meteor-phantomjs-tests.git 
```

Be aware that you will either have to use git submodules or remove `.git` if you to have this in your git repository.

**Comment by merlinpatt** [comment] 2016-12-14 17:56
I had this same issue. @jbbr's fix of downgrading to 0.0.5 worked for me.

Are there any benefits I am missing by using the downgraded package?

**Comment by HenrikSkriver** [comment] 2016-12-14 17:56
Hi @jbbr 

I added `dispatch:phantomjs-tests@=0.0.5` to the packages file and ran the meteor test command with the `--allow-incompatible-update`  which solved the initial problem.

However, this error was shown:
`/root/.meteor/packages/dispatch_phantomjs-tests/.0.0.5.1ausijh++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

Running `sudo apt-get install libfontconfig` fixed that problem and now both server and client tests are running as expected.

@jbbr thank you for the workaround.

**Comment by aldeed** [comment] 2016-12-23 21:17
Just to clarify, this is definitely a Meteor issue. All I did was publish a new version of the phantomjs-tests package. It's the first time it was published since Meteor changed the way they handle binary packages, so that's what triggered it. But if `meteor npm rebuild` and other advice from MDG does not work, you will need to pester them for a fix.

**Comment by FinalDes** [comment] 2016-12-26 11:26
cannot use npm phanton js intead @aldeed ?

**Comment by aldeed** [comment] 2016-12-26 16:26
@FinalDes I'm not sure what package you mean, but they would all be binary so it won't make a difference.

**Comment by PositronicBrain** [comment] 2016-12-27 15:50
Same problem here, with meteor 1.4.2.3 and a newly created project. The command:

    meteor test --once --allow-superuser --driver-package=dispatch:mocha-phantomjs

Fails with

    /root/.meteor/packages/dispatch_phantomjs-tests/.0.0.7.15nvl5u++os+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: 1: /root/.meteor/packages/dispatch_phantomjs-tests/.0.0.7.15nvl5u++os+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string

**Comment by aldeed** [comment] 2016-12-27 17:15
@PositronicBrain yep, please pester MDG about this in the meteor/meteor repo. If more people complain, they will fix it.

**Comment by danstiner** [comment] 2017-01-07 04:27
Running `meteor npm rebuild` in the project directory did not help for me, but running `npm rebuild` in `~/.meteor/packages/dispatch_phantomjs-tests/.0.0.7.1k3403j++os+web.browser+web.cordova/npm` did fix things.

It seems odd the package has its own node_modules under the user .meteor directory, but from this discussion it seems that might be by design for meteor so I opened an issue against them to see if we can't get this fixed: https://github.com/meteor/meteor/issues/8225

**Comment by MuyBien** [comment] 2017-01-22 13:40
Hi everyone!!
Having the same exact issue. So I cannot valid my test on a CI :(
Waiting for a fix ;)

**Comment by aldeed** [comment] 2017-02-17 16:58
This should be fixed now that the underlying Meteor rebuild issue is fixed. It also will not be an issue anymore if you switch to the latest [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha) package, which is replacing mocha-phantomjs and supports additional browsers.

**Closed by aldeed** 2017-02-17 16:58 UTC
