### ISSUE TITLE
Error: Missing reporter to run tests

### ISSUE THREAD

**Issue by lorensr** [DispatchMe/meteor-mocha-phantomjs#14] opened 2016-05-10 00:58 UTC
Readme says the default is spec – do I need to install that along with `dispatch:mocha-phantomjs`? Via atmo or npm?

```
> meteor test --once --driver-package dispatch:mocha-phantomjs

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
I20160509-20:55:14.591(-4)?                   
I20160509-20:55:14.592(-4)? --------------------------------
=> Started your app.

=> App running at: http://localhost:3000/
I20160509-20:55:14.672(-4)? ----- RUNNING SERVER TESTS -----
I20160509-20:55:14.672(-4)? --------------------------------
I20160509-20:55:14.672(-4)? 
I20160509-20:55:14.672(-4)? 
I20160509-20:55:14.673(-4)? 
I20160509-20:55:14.673(-4)?   0 passing (0ms)
I20160509-20:55:14.673(-4)? 
I20160509-20:55:14.674(-4)? 
I20160509-20:55:14.674(-4)? --------------------------------
I20160509-20:55:14.674(-4)? ----- RUNNING CLIENT TESTS -----
I20160509-20:55:14.674(-4)? --------------------------------
I20160509-20:55:14.675(-4)? 
I20160509-20:55:14.675(-4)? Kadira: completed instrumenting the app
I20160509-20:55:14.675(-4)? Beginning DB Migrations
I20160509-20:55:14.675(-4)?   No expand migrations found
I20160509-20:55:16.922(-4)? 
I20160509-20:55:16.922(-4)? 
I20160509-20:55:16.934(-4)? Missing analyticsSettings in Meteor.settings.public
I20160509-20:55:16.951(-4)?   appointmentCard

I20160509-20:55:16.965(-4)?     ✓ renders correctly with simple data
I20160509-20:55:16.965(-4)? 
I20160509-20:55:16.966(-4)? 
I20160509-20:55:16.966(-4)?   1 passing (46ms)
I20160509-20:55:16.966(-4)? 
I20160509-20:55:16.975(-4)? stdout: 
I20160509-20:55:16.981(-4)? MochaRunner.runServerTests: Starting server side tests with run id 6hnmwHR7cdaPacfRF
W20160509-20:55:16.986(-4)? (STDERR) MochaRunner.runServerTests: failures: 0
I20160509-20:55:16.989(-4)? ClientServerReporter.constructor: Missing reporter to run tests. Use MochaRunner.setReporter(reporter) to set one.
I20160509-20:55:16.989(-4)? 
I20160509-20:55:16.989(-4)?   phantomjs://code/phantomjsScript.js:15 in onError
I20160509-20:55:16.989(-4)?     http://localhost:3000/packages/dispatch_mocha-phantomjs.js?hash=318f1fcf37511159af525b2afea1c3c2a6ad0fbf: 256
I20160509-20:55:16.989(-4)? 
I20160509-20:55:16.989(-4)?   phantomjs://code/phantomjsScript.js:17
I20160509-20:55:19.713(-4)? All client and server tests finished!
I20160509-20:55:19.713(-4)? 
I20160509-20:55:19.713(-4)? --------------------------------
I20160509-20:55:19.713(-4)? SERVER FAILURES: 0
I20160509-20:55:19.713(-4)? CLIENT FAILURES: 0
I20160509-20:55:19.714(-4)? --------------------------------
```

**Comment by aldeed** [comment] 2016-05-11 22:13
Are you able to create a simple app that reproduces this error? Not sure what the cause is.

**Comment by lorensr** [comment] 2016-05-11 23:42
Sorry, tried a simple repro, worked fine!

**Comment by Sanjo** [comment] 2016-05-12 07:34
I get this error when I have also `practicalmeteor:mocha` as dependency. When I remove `practicalmeteor:mocha` the error goes away.

**Comment by lorensr** [comment] 2016-05-12 20:54
Thanks Sanjo! My original repo does also have that package. 

My repro fails when I add it, although without printing the same error:

https://github.com/lorensr/14

```
meteor test --driver-package dispatch:mocha-phantomjs
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20160512-16:52:15.505(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20160512-16:52:15.506(-4)? ** you still have autopublish turned on. Because autopublish is still
I20160512-16:52:15.506(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20160512-16:52:15.507(-4)? ** will still be sent to all clients.
I20160512-16:52:15.507(-4)? **
I20160512-16:52:15.507(-4)? ** Turn off autopublish by removing the autopublish package:
I20160512-16:52:15.507(-4)? **
I20160512-16:52:15.507(-4)? **   $ meteor remove autopublish
I20160512-16:52:15.507(-4)? **
I20160512-16:52:15.507(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20160512-16:52:15.507(-4)? ** for each collection that you want clients to see.
I20160512-16:52:15.507(-4)? 
I20160512-16:52:15.508(-4)? 
I20160512-16:52:15.508(-4)? --------------------------------
I20160512-16:52:15.508(-4)? ----- RUNNING SERVER TESTS -----
I20160512-16:52:15.508(-4)? --------------------------------
I20160512-16:52:15.508(-4)? 
I20160512-16:52:15.508(-4)? 
I20160512-16:52:15.509(-4)? 
I20160512-16:52:15.509(-4)?   0 passing (0ms)
I20160512-16:52:15.509(-4)? 
I20160512-16:52:15.509(-4)? 
I20160512-16:52:15.509(-4)? --------------------------------
I20160512-16:52:15.509(-4)? ----- RUNNING CLIENT TESTS -----
I20160512-16:52:15.509(-4)? --------------------------------
I20160512-16:52:15.509(-4)? 
I20160512-16:52:16.488(-4)? 
I20160512-16:52:16.489(-4)? 
I20160512-16:52:16.504(-4)?   test
I20160512-16:52:16.514(-4)? MochaRunner.runServerTests: Starting server side tests with run id o7spuTJGLjxywiCpn
W20160512-16:52:16.530(-4)? (STDERR) MochaRunner.runServerTests: failures: 0
I20160512-16:52:31.071(-4)? MochaRunner.runServerTests: Starting server side tests with run id ZrEve6HKJravywxLv
W20160512-16:52:31.079(-4)? (STDERR) MochaRunner.runServerTests: failures: 0
I20160512-16:52:46.997(-4)? All client and server tests finished!
I20160512-16:52:46.997(-4)? 
I20160512-16:52:46.997(-4)? --------------------------------
I20160512-16:52:46.997(-4)? SERVER FAILURES: 0
I20160512-16:52:46.997(-4)? CLIENT FAILURES: 2
I20160512-16:52:46.997(-4)? --------------------------------
=> Exited with code: 2
```

**Comment by lorensr** [comment] 2016-05-19 19:37
Let's see whether this is fixed after this: https://github.com/practicalmeteor/meteor-mocha/issues/23

**Comment by namirsab** [comment] 2016-06-02 22:17
When I don't have `practicalmeteor:mocha` installed i see this error:
```
W20160602-23:56:27.130(2)? (STDERR)
W20160602-23:56:27.131(2)? (STDERR) /home/namir/.meteor/packages/meteor-tool/.1.3.2_4.dcqb20++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fib
ers/future.js:267
W20160602-23:56:27.131(2)? (STDERR)                                             throw(ex);
W20160602-23:56:27.131(2)? (STDERR)                                                   ^
W20160602-23:56:27.131(2)? (STDERR) Error: Can't find npm module 'meteor/practicalmeteor:mocha'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160602-23:56:27.132(2)? (STDERR)     at Object.Npm.require (/tmp/meteor-test-run12v59rq/.meteor/local/build/programs/server/boot.js:195:17)
W20160602-23:56:27.132(2)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160602-23:56:27.132(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
W20160602-23:56:27.132(2)? (STDERR)     at meteorInstall.imports.TreeNode.TreeNode.spec.js (imports/TreeNode/TreeNode.spec.js:6:1)
W20160602-23:56:27.132(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-23:56:27.132(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-23:56:27.132(2)? (STDERR)     at /tmp/meteor-test-run12v59rq/.meteor/local/build/programs/server/app/app.js:591:1

W20160602-23:56:27.132(2)? (STDERR)     at /tmp/meteor-test-run12v59rq/.meteor/local/build/programs/server/boot.js:283:10
W20160602-23:56:27.133(2)? (STDERR)     at Array.forEach (native)
W20160602-23:56:27.133(2)? (STDERR)     at Function._.each._.forEach (/home/namir/.meteor/packages/meteor-tool/.1.3.2_4.dcqb20++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_
bundle/server-lib/node_modules/underscore/underscore.js:79:11)
```

**Comment by Ben305** [comment] 2016-07-13 16:08
Unfortunately, this seems still to be an issue. I can easily reproduce this with the above repository and the latest versions.

**Comment by aldeed** [comment] 2017-02-17 16:53
Closing since this repo is being replaced by the updated [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). Please repost in that repo if this is still an issue.

**Closed by aldeed** 2017-02-17 16:53 UTC
